version: '3.8'


services:

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: database_1
      POSTGRES_USER: sagar
      POSTGRES_PASSWORD: hp1234
    ports:
      - "5433:5432"

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: hospital-management
    volumes:
      - .:/hospital-management
    ports:
      - "8000:8000"
    depends_on:
      - db
