# Generated by Django 5.0.6 on 2024-05-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='profile_pic',
        ),
    ]
