# Generated by Django 5.0.6 on 2024-06-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_myuser_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myuser',
        ),
    ]
