# Generated by Django 5.0.6 on 2024-06-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_doctor_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
    ]
