# Generated by Django 5.0.6 on 2024-06-30 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_timeslot_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.patient'),
        ),
    ]
