# Generated by Django 5.0.6 on 2024-06-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_timeslot_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
