# Generated by Django 5.0.6 on 2024-07-04 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_timeslot_status_delete_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='status',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('prescription', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.timeslot')),
            ],
        ),
    ]
