# Generated by Django 5.0.6 on 2024-07-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_timeslot_prescription_remove_timeslot_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
