# Generated by Django 5.0.6 on 2024-07-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_appointment_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='describe_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
