# Generated by Django 5.0.6 on 2024-07-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_appointment_describe_problem_appointment_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, null=True),
        ),
    ]
